import Link from "next/link";
import type {ReactElement} from "react";

export default function Head(): ReactElement {
    return (
        <>
            <title>PikaReed</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
            <Link rel="icon" href="/pikareed-logo.ico" />
        </>
    );
}
